version: "3.3"
services:
  scion-step-proxy:
    build: scion-step-proxy
    # TODO: Fix volumes match args
    command: -seedFile=/etc/step-ca/proxy-seeds.json -jwtSecrect=/etc/scion/private-ca1.pem -trcPath=/etc/scion/certs -certDuration=72h
    volumes:
      - "./step-ca:/etc/step-ca"
      - "/etc/scion:/etc/scion"
    environment:
      - "DATABASE_PATH=/etc/step-ca/step-proxy.sqlite"
      - "DATABASE=sqlite"
      # TODO: Path to /etc/step-ca for /usr/bin
  smallstep-ca-scion:
    build: smallstep-ca-scion
    command: --password-file=/etc/step-ca/.step/pw.key /etc/step-ca/.step/config/ca.json
    volumes:
      - "./step-ca:/etc/step-ca"
    environment:
      - "SCION_AS_SUBJECT_COUNTRY=DE"
      - "SCION_AS_SUBJECT_ORGANIZATION=OVGU Magdeburg for GEANT"
      - "SCION_AS_SUBJECT_COMMONNAME=SCION Education Network CA"
      - "SCION_AS_PROVISIONER=71-20295" # Needs to be ISD-AS
  smallstep-cli-scion:
    build: smallstep-cli-scion
    environment:
      - "CA_ROOT_CERT=/etc/step-ca/root.crt"
      - "CA_ROOT_KEY=/etc/step-ca/root.key"
    volumes:
      - "./step-ca:/etc/step-ca"
      - "/etc/scion:/etc/scion"
    # TODO: Do ca init once, otherwise just sleep until container exits, provides playground to work with certs
