
isd = {{ISD}}
description = "{{NAME}}"
serial_version = 1
base_version = 1
# We only have 1 core AS at the moment
voting_quorum = 1 

core_ases = ["{{AS}}"]
authoritative_ases = ["{{AS}}"]
# votes = [2] # TODO: 5?
cert_files = ["ISD{{ISD}}-{{AS}}.root.crt", "ISD{{ISD}}-{{AS}}.regular.crt", "ISD{{ISD}}-{{AS}}.sensitive.crt"]
[validity]
    not_before = {{NOW}}
    validity = "365d" # 1826 results in an error that the validity is not covered by a certificate